remote_theme: daattali/beautiful-jekyll@6.0.1

title: "Violet M. Kimble, PhD"
author: "Violet M. Kimble, PhD"

navbar-links:
  Research: "research"
  Publications: "publications"
  CV: "/img/CV.pdf"

avatar: "/img/Violet.jpg"
round-avatar: true

social-network-links:
  email: "violet.kimble@utah.edu"
  github: VioletKimble
  linkedin: violet-kimble
  ORCID: "0000-0002-5075-9643"
  google-scholar: "bbcI0CIAAAAJ"

url-pretty: "violetkimble.github.io"
title-on-all-pages: true

navbar-col: "#252525"
navbar-text-col: "#FFFFFF"
navbar-border-col: "#666666"
footer-col: "#252525"
hover-col: "#006D77"

site-css:
  - "/assets/css/custom-styles.css"

timezone: "America/Denver"
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
      show-avatar: true

plugins:
  - jekyll-paginate
  - jekyll-sitemap
