remote_theme: daattali/beautiful-jekyll
title: Stephanie Noble
author: Stephanie Noble
description: All things academia.

# --- List of links in the navigation bar --- #

navbar-links:
  Projects: "projects"
  CV: /img/SMN_CV_June_2021.pdf
  Publications: "https://scholar.google.com/citations?user=JxQdvn4AAAAJ&hl=en&oi=sra"

# --- Logo --- #

avatar: "/img/profile_photo_2018_square.jpeg"

# --- Cover image --- #

cover-img: "/img/net_banner.gif"

# --- Footer options --- #

social-network-links:
  email: "stephanie.noble@yale.edu"
  github: sNeuroble
  twitter: sNeuroble
  linkedin: sNeuroble
  
after-content: contact
  
# --- Colours / background image --- #

navbar-col: "#252525"
navbar-text-col: "#0085A1"
navbar-border-col: "#666666"
# page-col: "#FFFFFF"
# text-col: "#404040"
# link-col: "#008AFF"
hover-col: "#00BFF7"
# hover-col: "#404040"
footer-col: "#252525"
# footer-text-col: "#777777"
# footer-link-col: "#404040"
# navbar-img: "/img/clanky_banner.gif"
# mobile-theme-col: "#0085A1"


defaults:
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true
