remote_theme: daattali/beautiful-jekyll
title: Violet Kimble 
author: Violet Kimble
description: All things academia.

# --- List of links in the navigation bar --- #

navbar-links:
  Research: "research"
  CV: /img/CV.Violet.Dec '21.pdf
  Publications: "https://scholar.google.com/citations?user=2mQJ_CUAAAAJ&hl=en"

# --- Logo --- #

avatar: "/img/Violet.jpg"

# --- Cover image --- #

cover-img: "/img/brain_banner.gif"

# --- Footer options --- #

social-network-links:
  email: "violet.kimble@yale.edu"
  github: VioletKimble
  twitter: violet_kimble
  linkedin: violet-k
  
  
after-content: contact
  
# --- Colours / background image --- #

navbar-col: "#252525"
navbar-text-col: "#FFFFFF"
navbar-border-col: "#666666"
# page-col: "#FFFFFF"
# text-col: "#404040"
# link-col: "#00229A"
hover-col: "#00BFF7"
# hover-col: "#404040"
footer-col: "#252525"
# footer-text-col: "#777777"
# footer-link-col: "#404040"
# navbar-img: "/img/clanky_banner.gif"
# mobile-theme-col: "#00229A"


defaults:
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true
